name: hardware-ci self-test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/manufacturing.yml"
      - ".github/workflows/fpga.yml"
      - ".github/workflows/self-test.yml"
      - "test/fixture/**"
      - "test/fpga/**"
      - "test/fpga-ecp5/**"
      - "test/fpga-ecp5/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/manufacturing.yml"
      - ".github/workflows/fpga.yml"
      - ".github/workflows/self-test.yml"
      - "test/fixture/**"
      - "test/fpga/**"

permissions:
  contents: write

jobs:
  fixture:
    uses: Ploos-AS/hardware-ci/.github/workflows/manufacturing.yml@main
    with:
      board_path: test/fixture/fixture.kicad_pcb
      publish_release: false

  fpga-fixture:
    uses: Ploos-AS/hardware-ci/.github/workflows/fpga.yml@test/fpga-self-test
    with:
      board: upduino-v3.1
      working_directory: test/fpga
      test_target: test
      build_target: build
      bitstream_path: test/fpga/fixture.bin

  ecp5-fixture:
    uses: Ploos-AS/hardware-ci/.github/workflows/fpga.yml@feature/fpga-ecp5
    with:
      board: ecp5
      working_directory: test/fpga-ecp5
      test_target: test
      build_target: build
      bitstream_path: test/fpga-ecp5/fixture.bit
